#ifndef GT_NET_DEFINITION_H_
#define GT_NET_DEFINITION_H_

/* THIS FILE CAN BE REPLACE BY XML */

#define BUF_SIZE		4*1024


#define TCP_MODE_ENABLE		1			// IF TCP MODE = 0, WILL USE UDP MODE
#define BIND_ADDRESS	127.0.0.1
#define BIND_PORT		7777

#endif // GT_NET_DEFINITION_H_
