#ifndef GT_NET_DEFINITION_H_
#define GT_NET_DEFINITION_H_


/* ERROR CODE */

enum GT_ERROR_CODE {
    GT_ERROR_SUCCESS = 0,
};

/* THIS FILE CAN BE REPLACE BY JSON */

#define BUF_SIZE		    4*1024


#define TCP_MODE_ENABLE		1
#define BIND_ADDRESS	    "127.0.0.1"
#define BIND_PORT		    7777

#endif // GT_NET_DEFINITION_H_
