#ifndef GT_NET_IOCONTEXT_H_
#define GT_NET_IOCONTEXT_H_


enum IO_EVENT_TYPE {
	IO_EVENT_ACCEPT_COMPLETE = 0,
    IO_EVENT_READ_COMPLETE,
    IO_EVENT_READ_REQUEST,
    IO_EVENT_WRITE_COMPLETE,
    IO_EVENT_WRITE_REQUEST
};

struct PER_SOCKET_CONTEXT {

};

struct PER_IO_CALL_DATA {

};

#endif // GT_NET_IOCONTEXT_H_
