#ifndef GT_NET_DEFINITION_H_
#define GT_NET_DEFINITION_H_


enum GT_ERROR_CODE {
    GT_ERROR_FAILED = -1,
    GT_ERROR_SUCCESS = 0,
};

enum GT_LOG_LEVEL {
    GT_LOG_LEVEL_INFO = 0,
    GT_LOG_LEVEL_WARNING = 1,
    GT_LOG_LEVEL_ERROR = 2,
	GT_LOG_LEVEL_OFF = 3,
    GT_LOG_LEVEL_ALL = GT_LOG_LEVEL_INFO
};

enum IO_EVENT_TYPE {
	IO_EVENT_NULL = -1,
	IO_EVENT_ACCEPT_COMPLETE,
	IO_EVENT_READ_COMPLETE,
	IO_EVENT_WRITE_COMPLETE
};


#endif // GT_NET_DEFINITION_H_
